services:
  openWebUI:
    image: ghcr.io/open-webui/open-webui:main
    restart: unless-stopped
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - open-webui-local:/app/backend/data
    environment:
      - WEBUI_AUTH=False
      - ENABLE_OLLAMA_API=False
      - ENABLE_OPENAI_API=True
      - OPENAI_API_BASE_URL=http://aws-bedrock-gateway/api/v1
      - OPENAI_API_KEY=bedrock

  aws-bedrock-gateway:
    build: 
      context: ./bedrock-access-gateway/src/
      dockerfile: Dockerfile_ecs
    restart: unless-stopped
    ports: 
      - 8000:80
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - AWS_REGION
      - DEBUG=true

volumes:
  open-webui-local:
